# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a0d0005680feac761ae262a9fc638adf17d5c1ca

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token a0d0005680feac761ae262a9fc638adf17d5c1ca

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2020-10-01
Content-Type: application/json

### удаление объявления
DELETE  {{baseUrl}}/advertisements/17/
Content-Type: application/json
Authorization: Token a0d0005680feac761ae262a9fc638adf17d5c1ca

###

# добавить в черновик
PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token a0d0005680feac761ae262a9fc638adf17d5c1ca

{
  "status": "DRAFT"
}
###
# получение объявлений в черновике
GET {{baseUrl}}/advertisements/?status=DRAFT
Authorization: Token a0d0005680feac761ae262a9fc638adf17d5c1ca

###
# добавить в избранное
POST  {{baseUrl}}/advertisements/18/add_fav/
Authorization: Token c271be880682caad811fc649c5e7a0e0f3311878

###
# просмотреть избранное 
GET {{baseUrl}}/advertisements/get_fav
Authorization: Token c271be880682caad811fc649c5e7a0e0f3311878